// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAypt3hLE3OQ_vXjQrmC9XsMAQ1qoEk_2E',
    appId: '1:120654422099:web:776a3689c9e5a77d07a6a6',
    messagingSenderId: '120654422099',
    projectId: 'languagelearningapp-b01b9',
    authDomain: 'languagelearningapp-b01b9.firebaseapp.com',
    storageBucket: 'languagelearningapp-b01b9.firebasestorage.app',
    measurementId: 'G-4ZQ0XBQRJD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3m6LMUg0EvuTk2MPv460HKqXPQAwzm6s',
    appId: '1:120654422099:android:fe185c1a63774a1b07a6a6',
    messagingSenderId: '120654422099',
    projectId: 'languagelearningapp-b01b9',
    storageBucket: 'languagelearningapp-b01b9.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAypt3hLE3OQ_vXjQrmC9XsMAQ1qoEk_2E',
    appId: '1:120654422099:web:a9c76a798d8c8d4b07a6a6',
    messagingSenderId: '120654422099',
    projectId: 'languagelearningapp-b01b9',
    authDomain: 'languagelearningapp-b01b9.firebaseapp.com',
    storageBucket: 'languagelearningapp-b01b9.firebasestorage.app',
    measurementId: 'G-G0991WT0FR',
  );
}
